version: "3.7"

services:
  fefu-delivery-nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: 'fefu-delivery-nginx'
    working_dir: /app
    ports:
      - "${NGINX_HTTP_PORT:-7777}:80"
    volumes:
      - ./:/app:delegated
    depends_on:
      - 'fefu-delivery-php-fpm'
    environment:
      NGINX_HOST: "${NGINX_HOST:-localhost:7777}"
      NGINX_HTTP_PORT: "${NGINX_HTTP_PORT:-7777}"

  fefu-delivery-php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile.dev
    container_name: 'fefu-delivery-php-fpm'
    working_dir: /app
    restart: on-failure
    volumes:
      - ./:/app:delegated
    depends_on:
      - 'fefu-delivery-mysql'
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}"

  fefu-delivery-mysql:
    image: mysql:8.0.21
    container_name: 'fefu-delivery-mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - data-fefu-delivery-mysql:/var/lib/mysql:delegated
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:delegated

volumes:
  data-fefu-delivery-mysql: {}
